<span class="menu-item-icon fa fa-search fa-fw"></span>
<form class="site-search-form" target="_blank" action="http://search.jasongj.com/cse/search" autocomplete="off" >
  <input type="text" id="bdcsMain" name="q" value="{{ __('menu.search') }}" onfocus="if(value == '{{ __('menu.search') }}'){value=''}" onblur="if(value == ''){value='{{ __('menu.search') }}'}"></input>
  <input type="hidden" name="s" value="11273528160680594791">
  <input type="hidden" name="entry" value="1">
</form>

